version: '3.4'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=morph
    volumes:
      - db:/var/lib/postgres

  discord-faucet-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: discord-faucet-bot:latest
    restart: unless-stopped
    container_name: 'morph-discord-bot'
    depends_on:
      - db
    command: >
      pnpm start:prod
    ports:
      - "6060:6060"
    environment:
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432

volumes: 
  db:
    